import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats 
{
	public static void main (String[] args) 
	{
		// Gets the two command-line arguments
		int num = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		///double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		boolean sucsess = false;
		boolean girl = false; // smaller than 0.5
		boolean boy = false; // bigger than 0.5
		int countchild = 0;
		int countfam = 0;
		double rnd = 0;
		int fam2 = 0;
		int fam3 = 0;
		int fam4 = 0;
		int max = 2;
		for (int i = 1; i <= num; i ++)
		{
			while (sucsess == false)
		    {
			   if ((girl && boy) == true)
			   {
				 break;
			   }
			   rnd = generator.nextDouble();;
			   if (rnd <= 0.5)
			   {
				 girl = true;
				 countchild ++;
				 System.out.print("g ");
			   }
			   else 
			   {
				 boy = true;
				 countchild ++;
				 System.out.print("b ");
			   }
			   if ((girl && boy) == true)
			   {
			     sucsess = true;
			     countfam += countchild;
			     if (countchild == 2)
			     {
			  	 fam2++;
			     }
			     else if (countchild == 3)
			     {
			  	 fam3++;
			     }
			     else fam4++;
			   }
		    }
		    
		    System.out.println();
		    System.out.println("You made it... and you now have " +countchild+ " children.");
		    girl = false;
		    boy = false;
		    sucsess = false;
		    countchild = 0;

		}
		if((fam2 >= fam3) && (fam2 >= fam4))
		{
			max=2;
		}
		else if((fam3 > fam2) && (fam3 > fam4))
		{
			max=3;
		}
		else 
		{
			max=4;
		}	
		double avg = ((double) countfam) / num;
		System.out.println("Average: " + avg + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + fam2);
		System.out.println("Number of families with 3 children: " + fam3);
		System.out.println("Number of families with 4 or more children: " + fam4);
		System.out.println("The most common number of children is " + max +".");
	}
}
